### ISSUE TITLE
[Feature]: Deleting addresses

### ISSUE THREAD

**Issue by pablogfb** [tastyigniter/ti-ext-user#10]
### What is the feature?

It would be interesting to add the possibility of deleting addresses.

The code is pretty simple, I can make it. Is there any outside implication? For example: is deleting an address going to break old orders?

### Version

3.0.6

**Comment by ryanmitchell** [comment]
Yes, delivery orders are mapped to address.
Maybe rather than deleting addresses they are hidden / archived?

**Comment by pablogfb** [comment]
Yes, soft delete then is a good solution. New field deleted: bolean.
 
It isn't a  common use case but in some situations might have sense get rid of old addresses.

I feel less confident handling migrations though...

**Comment by ryanmitchell** [comment]
```
            Schema::table('addresses', function (Blueprint $table) {
                $table->boolean('is_deleted')->default(false);
            });
```

**Comment by sampoyigi** [comment]
This issue looks fixed. Closing, but please reopen if it still occurs.
