### ISSUE TITLE
[Bug]:  Class "Illuminate\Support\Facades\RateLimiter" not found

### ISSUE THREAD

**Issue by JamesThanna** [tastyigniter/ti-ext-user#12]
### What happened?

When upgrading from 3.0.5 to the last pre release. We're seeing. the following error. When checking vendor for RateLimiter  within the Laravel vendor it's not there so not sure if the update of TI to Laravel 8 is complete. 

### What did you expect to happen?

Update should complete and I'm guessing RateLimiter should be showing. 

### Version

3.0.5

### Relevant log output

```shell
(1/1) Error
Class "Illuminate\Support\Facades\RateLimiter" not found

in Extension.php line 117
at Extension->configureRateLimiting()
in Extension.php line 21
at Extension->boot()
in ExtensionManager.php line 436
at ExtensionManager->bootExtension(object(Extension))
in ExtensionManager.php line 413
at ExtensionManager->bootExtensions()
in ServiceProvider.php line 93
at ServiceProvider->boot()
in BoundMethod.php line 36
at BoundMethod::Illuminate\Container\{closure}()
in Util.php line 37
```

**Comment by sampoyigi** [comment]
Have you updated the versions for Laravel and flame from your root composer.json?

**Comment by sampoyigi** [comment]
Not reproducible in the latest release. Please reopen this issue if it still occurs, with a set of reproducible steps.
