### ISSUE TITLE
[Feature]: Fix the subject of invitation email

### ISSUE THREAD

**Issue by Yukichan0528** [tastyigniter/ti-ext-user#13]
### What is the feature?

The subject of the user invitation email contains an extra '}'.
I want to make it a correct subject line.

invite.blade.php line 1
`subject = "Invitation to access {{ $site_name }}}"
`

### Version

3.0.6

**Comment by sampoyigi** [comment]
Thanks a lot for opening this issue! Would you like to submit a PR for this?

**Comment by Yukichan0528** [comment]
Sorry, this issue wasn't about the user extension, but about the Tasty Igniter itself.
I will submit the issue again.
