### ISSUE TITLE
[Bug]: Address Book postcode “The Postcode may not be greater than 11] characters.”

### ISSUE THREAD

**Issue by diverds1992** [tastyigniter/ti-ext-user#15]
### What happened?

When adding a postcode in user address book it gives error “The Postcode may not be greater than 11] characters.”

only in php 8

### What did you expect to happen?

the settings are min 2 max 11

### Version

Other (please detail)

### What browser are you seeing the problem on?

Chrome

### Relevant log output

```shell
Already got the fix, but can't pull request

components > AdressBook.php
line 48
[‘address.postcode’, ‘lang:igniter.user::default.account.label_postcode’, ‘required|min:2|max:11]’], change to [‘address.postcode’, ‘lang:igniter.user::default.account.label_postcode’, ‘required|min:2|max:11’],
```

**Comment by sampoyigi** [comment]
Fixed
